name: Site Accessibility Check

on:
  repository_dispatch:
    types: [gitlab-merge]

  workflow_dispatch:
    inputs:
      clean_cache:
        description: '是否清除 pnpm store 快取'
        required: true
        default: 'false'
      keep_report_files:
        description: '是否保留報告檔案'
        required: true
        default: 'true'
      base_url:
        description: '測試站點的 base URL(請填完整網址，例如：https://moda.gov.tw、http://localhost:3000)(目前不接受子路徑, 例如：https://www.xxx.xx/demoSite → www-xxx-xx.spec.cy.js)'
        required: true
        default: 'https://moda.gov.tw'
        type: choice
        options:
          - 'https://moda.gov.tw'
          - 'https://if540.github.io/accessibility-testing-with-cypress/react-app'
      spec_file:
        description: '測試檔案(可空，預設為 {base_url}.spec.cy.js, 例如：https://moda.gov.tw → moda-gov-tw.spec.cy.js)'
        required: false
        default: ''

jobs:
  a11y-site:
    runs-on: ubuntu-latest
    env: 
      payload: ${{ toJson(github.event.client_payload) || 'no payload' }}
      clean_cache: ${{ github.event.inputs.clean_cache }}
      keep_report_files: ${{ github.event.inputs.keep_report_files }}
      base_url: ${{ github.event.inputs.base_url }}
    # 0️⃣ 為前置作業
    steps:
      - name: 設定 spec_file
        run: |
          if [ -n "${{ github.event.inputs.spec_file }}" ]; then
            echo "spec_file=${{ github.event.inputs.spec_file }}" >> $GITHUB_ENV
          elif [ -n "${{ github.event.inputs.base_url }}" ]; then
            SPEC_FILE=$(echo "${{ github.event.inputs.base_url }}" | sed 's|https\?://||' | sed 's|/$||' | sed 's|:|---|g' | sed 's|\.|-|g' | sed 's|/|--|g' | sed 's|$|.spec.cy.js|')
            echo "spec_file=${SPEC_FILE}" >> $GITHUB_ENV
          fi

      # 0️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 0️⃣ 安裝 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 0️⃣ 假設 trigger 來自 GitLab，則印出 payload
      - name: Print payload
        run: |
          echo "payload: ${{ env.payload }}"
          if [ "${{ env.payload }}" != "no payload" ]; then
            echo "from_gitlab: $(echo '${{ env.payload }}' | jq -r '.from_gitlab // empty')"
          fi

      # 0️⃣ 清除舊的 pnpm store 快取
      - name: Remove old pnpm store cache
        if: ${{ env.clean_cache == 'true' }}
        run: rm -rf ~/.local/share/pnpm/store

      # 0️⃣ 快取 pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-store-${{ runner.os }}-

      # 1️⃣ 安裝專案依賴
      - name: Install dependencies
        run: pnpm install

      # 2️⃣ 從 gh-pages 拉取 reports-data/db.json (gh-pages 必須為開放狀態)
      - name: Fetch reports-data/db.json from gh-pages
        run: |
          curl -L https://github.com/if540/accessibility-testing-with-cypress/raw/gh-pages/reports-data/db.json -o public/data/db.json

      # 3️⃣ 開始執行 Cypress + Axe 測試(使用 headless 模式)
      - name: Run Accessibility Tests
        run: pnpm exec cross-env CYPRESS_BASE_URL=${{ env.base_url }}/ cypress run --spec 'cypress/e2e/sites/**/${{ env.spec_file }}' --headless
        continue-on-error: true

      # 4️⃣ 部署 Cypress report 到 gh-pages/a11y-reports
      - name: Deploy Accessibility Reports
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: cypress/reports
          destination_dir: a11y-reports
          keep_files: ${{ env.keep_report_files == 'true' }}
          commit_message: "Deploy A11y Reports [skip ci]"

      # 5️⃣ 部署 db.json
      - name: Deploy reports-data/db.json
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: public/data
          destination_dir: reports-data
          commit_message: "Deploy reports-data/db.json [skip ci]"
