# This is a basic workflow to help you get started with Actions

name: Test Accessibility

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # 安裝 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      # Runs a single command using the runners shell
      - name: Test Accessibility by specified url
        run: pnpm run test:a11y:url
        continue-on-error: true  # 失敗也會繼續下一步

      - name: Upload a11y report
        uses: actions/upload-artifact@v4
        with:
          name: a11y-report
          path: |
            cypress/reports/*.html
            cypress/reports/.jsons/*.json